/**
 *
 * $Id$
 */
package eu.piacere.doml.doml.concrete.validation;

import eu.piacere.doml.doml.concrete.ConcreteElement;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link eu.piacere.doml.doml.concrete.ConcreteElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConcreteElementValidator {
	boolean validate();

	boolean validateResourceName(String value);

	boolean validateConfigurationScript(String value);
	boolean validatePreexisting(Boolean value);
	boolean validateRefs(EList<ConcreteElement> value);
}
