/**
 *
 * $Id$
 */
package eu.piacere.doml.doml.concrete.validation;

import eu.piacere.doml.doml.concrete.Subnet;
import eu.piacere.doml.doml.infrastructure.Network;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link eu.piacere.doml.doml.concrete.Network}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NetworkValidator {
	boolean validate();

	boolean validateProtocol(String value);

	boolean validateAddressRange(String value);

	boolean validateSubnets(EList<Subnet> value);

	boolean validateMaps(EList<Network> value);

	boolean validateMaps(Network value);
}
