/**
 *
 * $Id$
 */
package eu.piacere.doml.doml.application.validation;

import eu.piacere.doml.doml.application.SoftwareInterface;

import eu.piacere.doml.doml.commons.Source;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link eu.piacere.doml.doml.application.SoftwareComponent}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SoftwareComponentValidator {
	boolean validate();

	boolean validateIsPersistent(Boolean value);
	boolean validateLicenseCost(Float value);
	boolean validateExposedInterfaces(EList<SoftwareInterface> value);
	boolean validateConsumedInterfaces(EList<SoftwareInterface> value);
	boolean validateSrc(Source value);
}
