/**
 *
 * $Id$
 */
package eu.piacere.doml.doml.optimization.validation;


/**
 * A sample validator interface for {@link eu.piacere.doml.doml.optimization.ObjectiveValue}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ObjectiveValueValidator {
	boolean validate();

	boolean validateCost(Float value);
	boolean validateAvailability(Float value);
	boolean validatePerformance(Float value);
}
