/**
 *
 * $Id$
 */
package eu.piacere.doml.doml.optimization.validation;

import eu.piacere.doml.doml.optimization.ObjectiveValue;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link eu.piacere.doml.doml.optimization.OptimizationSolution}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface OptimizationSolutionValidator {
	boolean validate();

	boolean validateObjectives(ObjectiveValue value);
	boolean validateDecisions(EList<String> value);
}
