/**
 *
 * $Id$
 */
package eu.piacere.doml.doml.commons.validation;

import eu.piacere.doml.doml.commons.DeployableElement;

import eu.piacere.doml.doml.infrastructure.InfrastructureElement;

/**
 * A sample validator interface for {@link eu.piacere.doml.doml.commons.Deployment}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DeploymentValidator {
	boolean validate();

	boolean validateComponent(DeployableElement value);
	boolean validateNode(InfrastructureElement value);
}
