/**
 *
 * $Id$
 */
package eu.piacere.doml.doml.commons.validation;

import eu.piacere.doml.doml.commons.Property;
import eu.piacere.doml.doml.commons.Requirement;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link eu.piacere.doml.doml.commons.DOMLElement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DOMLElementValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateDescription(String value);
	boolean validateAnnotations(EList<Property> value);
	boolean validateContributesTo(EList<Requirement> value);
}
