/**
 *
 * $Id$
 */
package eu.piacere.doml.doml.infrastructure.validation;

import eu.piacere.doml.doml.infrastructure.LoadBalancerKind;
import eu.piacere.doml.doml.infrastructure.SecurityGroup;
import eu.piacere.doml.doml.infrastructure.VirtualMachine;

/**
 * A sample validator interface for {@link eu.piacere.doml.doml.infrastructure.AutoScalingGroup}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AutoScalingGroupValidator {
	boolean validate();

	boolean validateMachineDefinition(VirtualMachine value);
	boolean validateMin(Integer value);
	boolean validateMax(Integer value);
	boolean validateSecurityGroup(SecurityGroup value);
	boolean validateLoadBalancer(LoadBalancerKind value);
}
