/**
 *
 * $Id$
 */
package eu.piacere.doml.doml.infrastructure.validation;

import eu.piacere.doml.doml.commons.Credentials;

import eu.piacere.doml.doml.infrastructure.ComputingGroup;
import eu.piacere.doml.doml.infrastructure.Location;
import eu.piacere.doml.doml.infrastructure.MonitoringRule;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link eu.piacere.doml.doml.infrastructure.ComputingNode}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ComputingNodeValidator {
	boolean validate();

	boolean validateArchitecture(String value);
	boolean validateOs(String value);
	boolean validateMemory_mb(Float value);
	boolean validateStorage(Float value);
	boolean validateCpu_count(Integer value);
	boolean validateCost(Float value);
	boolean validateLocation(Location value);
	boolean validateCredentials(Credentials value);
	boolean validateGroup(ComputingGroup value);
	boolean validateNodeSpecificMonitoring(EList<MonitoringRule> value);
	boolean validateDisabledMonitorings(EList<String> value);
}
