/**
 *
 * $Id$
 */
package eu.piacere.doml.doml.infrastructure.validation;

import eu.piacere.doml.doml.infrastructure.Container;
import eu.piacere.doml.doml.infrastructure.ContainerConfig;
import eu.piacere.doml.doml.infrastructure.ContainerHostConfig;
import eu.piacere.doml.doml.infrastructure.ContainerImage;

import eu.piacere.doml.doml.infrastructure.ContainerNetwork;
import eu.piacere.doml.doml.infrastructure.ContainerVolume;
import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link eu.piacere.doml.doml.infrastructure.Container}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContainerValidator {
	boolean validate();

	boolean validateGeneratedFrom(ContainerImage value);
	boolean validateHostConfigs(EList<ContainerHostConfig> value);

	boolean validateNetworks(EList<ContainerNetwork> value);

	boolean validateVolumes(EList<ContainerVolume> value);

	boolean validateDependsOn(EList<Container> value);

	boolean validateConfigs(EList<ContainerConfig> value);
}
