/**
 *
 * $Id$
 */
package eu.piacere.doml.doml.infrastructure.validation;

import eu.piacere.doml.doml.infrastructure.ComputingNode;
import eu.piacere.doml.doml.infrastructure.NetworkInterface;

/**
 * A sample validator interface for {@link eu.piacere.doml.doml.infrastructure.ContainerConfig}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContainerConfigValidator {
	boolean validate();

	boolean validateContainer_port(Integer value);
	boolean validateVm_port(Integer value);
	boolean validateHost(ComputingNode value);
	boolean validateIface(NetworkInterface value);
}
