/**
 *
 * $Id$
 */
package eu.piacere.doml.doml.infrastructure.validation;

import eu.piacere.doml.doml.infrastructure.Container;
import eu.piacere.doml.doml.infrastructure.ContainerNetwork;
import eu.piacere.doml.doml.infrastructure.ContainerVolume;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link eu.piacere.doml.doml.infrastructure.ContainerGroup}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ContainerGroupValidator {
	boolean validate();

	boolean validateServices(EList<Container> value);
	boolean validateNetworks(EList<ContainerNetwork> value);
	boolean validateVolumes(EList<ContainerVolume> value);
}
