/**
 *
 * $Id$
 */
package eu.piacere.doml.doml.infrastructure.validation;

import eu.piacere.doml.doml.infrastructure.InternetGateway;
import eu.piacere.doml.doml.infrastructure.NetworkInterface;
import eu.piacere.doml.doml.infrastructure.Subnet;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link eu.piacere.doml.doml.infrastructure.Network}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface NetworkValidator {
	boolean validate();

	boolean validateProtocol(String value);
	boolean validateAddressRange(String value);
	boolean validateConnectedIfaces(EList<NetworkInterface> value);
	boolean validateGateways(EList<InternetGateway> value);
	boolean validateSubnets(EList<Subnet> value);
}
