/**
 *
 * $Id$
 */
package eu.piacere.doml.doml.infrastructure.validation;

import eu.piacere.doml.doml.infrastructure.NetworkInterface;
import eu.piacere.doml.doml.infrastructure.VMImage;

/**
 * A sample validator interface for {@link eu.piacere.doml.doml.infrastructure.VirtualMachine}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VirtualMachineValidator {
	boolean validate();

	boolean validateSizeDescription(String value);
	boolean validateGeneratedFrom(VMImage value);

	boolean validateConfigInterface(NetworkInterface value);
}
